[package]
name = "linkme-impl"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Implementation detail of the linkme crate"
repository = "https://github.com/dtolnay/linkme"
documentation = "https://docs.rs/linkme"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"
