language: rust

rust:
  - nightly
  - beta
  - stable

matrix:
  include:
    - rust: 1.36.0
    - rust: nightly
      os: osx
    - rust: nightly
      os: windows
    - rust: nightly
      name: Cortex-M
      before_install: sudo apt-get install -y qemu-system-arm
      install: rustup target add thumbv7m-none-eabi
      script: cd tests/cortex && cargo run --release
    - rust: 1.31.0
      script: cargo check

script:
  - cargo test
  - cargo test --release
