[package]
name = "linkme"
version = "0.1.4"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Safe cross-platform linker shenanigans"
repository = "https://github.com/dtolnay/linkme"
documentation = "https://docs.rs/linkme"
readme = "README.md"
edition = "2018"

[dependencies]
linkme-impl = { version = "=0.1.4", path = "impl" }

[dev-dependencies]
rustversion = "0.1"
trybuild = "1.0"

[workspace]
members = ["impl", "tests/cortex"]
